### ISSUE TITLE
Version 1.11 action items

### ISSUE THREAD

**Issue by jlstevens** [pyviz/holoviews#1380]
**Edit**: Updated target from 1.7.1 to 1.8

Instead of filing lots of trivial issues with trivial fixes, I thought it might be good to build a TODO list for 1.8. The plan is to have a polished and announced 1.8 before 1.9 (sets up deprecation wanrings) before 2.0 where we can clean things up and break backwards compatibility in a few places.

I've tentatively assigned these tasks to Philipp [PR], Jim [JB] and myself [JL].

## Urgent docs and website work

- [x]  Make OptsMagic warn and display for invalid options [Merged PR #1375]  [JL]
- [x] Update the GIF linked to in the README to show a nice streams example. [ Issue #960] [PR]
- [x] Rework the README and features list entirely [JB?]
- [ ] Update the droplet to use latest bokeh to fix automated website builds. [JL]
- [ ] Add buildbot step to clear out JSON files on droplet [JL]
- [x] Polish the Streams and Linked Streams notebooks [JL,PR]
- [x] Remove references to mpld3 [Issue #1378]
- [x] Update FAQ [Issue #1078]
- [x] Make the updated website live.  [JL,PR]

## Docs and tutorial wishlist

- [x] Get streams-only examples displaying the first frame on the website.
- [x] Split up the Elements tutorials into separate notebooks.  [Issue #879]
- [ ] Setup testing for the new notebooks
- [x] Polish tutorial about Renderers and Plots [PR #1124]
- [x] Rework the Showcase notebook entirely     [Issue #1354]
- [x] Rework the Introduction notebook entirely. [Issue #1354]
- [ ] Set up a section for a bokeh style release pages
- [ ] Add a Roadmap page?

## Additions

These should all be quick things we've already discussed and know how to do. They can be assigned to 1.8 if they are more work than expected.

- [x] Bug fix in export [Issue #1381]
- [x] Add the 'default' dimension to ``Dimension`` [Issue #704]
- [x] Add Philipp's ``Periodic`` stream which I think it is a nice idea.
- [x] Add a ``Drag`` stream or get a drag stream example working.
- [x] Allow access to last arguments of Callable [Issue #1307]
- [x] Parameter to Dimensions utility [Issue #1190] (Currently assigned to 2.0 but easy to do earlier)

I'm happy to add to this list if you have more suggestions!

**Comment by jlstevens** [comment]
I've now added links to the relevant issues PRs. 

I think addressing the list above would be a very reasonable to do in short timeframe for 1.7.1 as these are all fairly small tasks.

**Comment by jlstevens** [comment]
@philippjfr @jbednar If you agree with this list, I can also assign the relevant issues/PRs to a 1.7.1 milestone due in say a week?

**Comment by philippjfr** [comment]
Sounds good to me.

**Comment by jlstevens** [comment]
We can also discuss our plan for #1379 here...

**Comment by jbednar** [comment]
Looks good, though I don't think things need to be in the above list if they are already issues tagged 1.7.1 in github...

**Comment by jlstevens** [comment]
Right, the purpose of this issue is three-fold:

1. Have a place to discuss 1.7.1.
2. Decide what we want to happen for 1.7.1 and get an overview of the work involved, especially in terms of the documentation needed.
3. Figure out what we want to do for 1.7.1 so I can tag the issues with the corresponding milestone

Seeing as we as we seem to have agreed on a plan, I'll move to step 3...

**Comment by jlstevens** [comment]
This is now the TODO list for 1.8 which will feature all the docs, a nice new website and an announcement. In addition to the items above, we need to:

- [ ] Implement our new docs plan outlined in #1379 . A lot of the work in the original TODO list is covered by this. At minimum we need the 'Getting Started' section and the core user guides.
- [ ] Get the elements gallery running. 
- [ ] Implement the new styles for 2.0 (need to check the current matplotlib rc file)
- [ ] Offer a way to restore the current styles for existing users.
- [ ] Adapt the bokeh sphinx theme and build the website with the new styles.

**Comment by jbednar** [comment]
> Offer a way to restore the current styles for existing users.

A suggestion: If we make it simple for users to select a certain style at the start of their notebook or app (e.g. ``hv.notebook_extension(... theme='hv1.7')``, we could recommend that a good practice for long-lived code meant to be reproducible would be to specify that style explicitly.  If not set, the appearance of plots could change over hv versions, as we make improvements that we want to be sure new users always can make use of.  But if set, we would do our very best to ensure that the given style does *not* change, even for improvements.  That way we could always be looking forward, while allowing users to declare that this particular work should not move forward until explicitly requested.  Basically, we could suggest that users pin this style at its current value.

**Comment by jlstevens** [comment]
Something like that does seem reasonable although the ``notebook_extension`` should then hook into something that isn't notebook specific to actually set the theme.

**Comment by jbednar** [comment]
Right; the notebook_extension would just be one way to call into this general mechanism.

**Comment by jlstevens** [comment]
I.8 is released! 🎉 

I've ticked off most of the boxes. Here are the remaining items:

* [ ] Update the droplet to use latest bokeh to fix automated website builds. [JL]
* [ ]  Add buildbot step to clear out JSON files on droplet [JL]
* [ ]  Setup testing for the new notebooks
* [ ]  Polish tutorial about Renderers and Plots [PR #1124]
* [ ]  Set up a section for a bokeh style release pages
* [ ]  Add a Roadmap page?
* [ ]  Add the 'default' dimension to Dimension [Issue #704]
* [ ]  Parameter to Dimensions utility [Issue #1190] (Currently assigned to 2.0 but easy to do earlier)

@philippjfr @jbednar I'll close this issue now but the items above without associated issues/PRs should be discussed and either discarded as ideas or assigned to issues.

**Comment by jlstevens** [comment]
Probably safer to reassign to 1.8.1 than close this issue now...

**Comment by jlstevens** [comment]
Other than the renderers tutorial, the outstanding items still need to be done (especially notebook testing!) but that isn't going to happen for 1.10. Bumping to the 1.11 milestone and renaming the issue.

**Comment by philippjfr** [comment]
Most of the infrastructure based tasks here are outdated or captured elsewhere, I do think we should add a Roadmap but I think that should be a separate issue now.
